import AudioCommon
import Foundation
import MLX
import MLXNN
import XCTest

@testable import ChatterboxTTS

/// Component + integration gates for the S3Gen waveform stage.
///
/// Goldens (generated by /tmp/cbx_s3gen_golden.py with the local /tmp/cbx-fp16
/// bundle) drive three checks:
///   1. CAMPPlus x-vector vs `cbx_s3_embedding` (cosine > 0.999).
///   2. HiFTGenerator on the golden flow mel produces a wav of the golden length.
///   3. flow(golden speech tokens + ref) mel vs `cbx_s3_mel` (cosine — reported;
///      seeded noise + loaded conformer blocks should make it reproducible).
final class S3GenIntegrationTests: XCTestCase {
    private let bundle = "/tmp/cbx-fp16/model.safetensors"
    private let goldenJSON = "/tmp/cbx_s3gen_golden.json"
    private let embeddingF32 = "/tmp/cbx_s3_embedding.f32"
    private let promptFeatF32 = "/tmp/cbx_s3_prompt_feat.f32"
    private let melF32 = "/tmp/cbx_s3_mel.f32"
    private let wavF32 = "/tmp/cbx_s3_wav.f32"
    private let refWav = "/tmp/clone_reference.wav"

    // MARK: - helpers

    private func readF32(_ path: String) throws -> [Float] {
        let d = try Data(contentsOf: URL(fileURLWithPath: path))
        return d.withUnsafeBytes { Array($0.bindMemory(to: Float.self)) }
    }

    private func cosine(_ a: [Float], _ b: [Float]) -> Double {
        let n = min(a.count, b.count)
        var dot = 0.0, na = 0.0, nb = 0.0
        for i in 0 ..< n {
            dot += Double(a[i]) * Double(b[i])
            na += Double(a[i]) * Double(a[i])
            nb += Double(b[i]) * Double(b[i])
        }
        guard na > 0, nb > 0 else { return 0 }
        return dot / (na.squareRoot() * nb.squareRoot())
    }

    /// Read a mono 16-bit or 32-bit-float PCM WAV → 24 kHz [Float] not required;
    /// the reference is already 24 kHz mono. Returns (samples, sampleRate).
    private func loadWav(_ path: String) throws -> (samples: [Float], sr: Int) {
        let data = try Data(contentsOf: URL(fileURLWithPath: path))
        return data.withUnsafeBytes { raw -> (samples: [Float], sr: Int) in
            let bytes = raw.bindMemory(to: UInt8.self)
            func u32(_ o: Int) -> UInt32 {
                UInt32(bytes[o]) | UInt32(bytes[o + 1]) << 8
                    | UInt32(bytes[o + 2]) << 16 | UInt32(bytes[o + 3]) << 24
            }
            func u16(_ o: Int) -> UInt16 { UInt16(bytes[o]) | UInt16(bytes[o + 1]) << 8 }
            var pos = 12  // skip RIFF + WAVE
            var sr = 24000
            var audioFormat: UInt16 = 1
            var bits: UInt16 = 16
            var samples: [Float] = []
            while pos + 8 <= bytes.count {
                let id = String(bytes: (0..<4).map { bytes[pos + $0] }, encoding: .ascii) ?? ""
                let size = Int(u32(pos + 4))
                let body = pos + 8
                if id == "fmt " {
                    audioFormat = u16(body)
                    sr = Int(u32(body + 4))
                    bits = u16(body + 14)
                } else if id == "data" {
                    let end = min(body + size, bytes.count)
                    if audioFormat == 3 || bits == 32 {
                        var o = body
                        while o + 4 <= end {
                            let bits32 = u32(o)
                            samples.append(Float(bitPattern: bits32))
                            o += 4
                        }
                    } else {
                        var o = body
                        while o + 2 <= end {
                            let s = Int16(bitPattern: u16(o))
                            samples.append(Float(s) / 32768.0)
                            o += 2
                        }
                    }
                }
                pos = body + size + (size & 1)
            }
            return (samples, sr)
        }
    }

    /// Resolve the original PyTorch checkpoint that carries the conformer blocks.
    private func conformerWeightsURL() -> URL? {
        let base = ("~/.cache/huggingface/hub/models--ResembleAI--chatterbox/snapshots" as NSString)
            .expandingTildeInPath
        let fm = FileManager.default
        guard let snaps = try? fm.contentsOfDirectory(atPath: base) else { return nil }
        for snap in snaps {
            let p = URL(fileURLWithPath: base).appendingPathComponent(snap)
                .appendingPathComponent("s3gen.safetensors")
            if fm.fileExists(atPath: p.path) { return p }
        }
        return nil
    }

    /// Load the full S3Gen stage from the local bundle (+ conformer blocks).
    private func loadS3Gen() throws -> (ChatterboxS3Gen, [String: Any]) {
        let fm = FileManager.default
        for p in [bundle, goldenJSON, refWav] where !fm.fileExists(atPath: p) {
            throw XCTSkip("missing \(p); run /tmp/cbx_s3gen_golden.py")
        }
        // S3TokenizerV2 weights (shared repo cache).
        let s3tokBase = ("~/.cache/huggingface/hub/models--mlx-community--S3TokenizerV2/snapshots"
            as NSString).expandingTildeInPath
        guard let snaps = try? fm.contentsOfDirectory(atPath: s3tokBase),
              let snap = snaps.first
        else { throw XCTSkip("S3TokenizerV2 weights not cached") }
        let s3tokWeights = URL(fileURLWithPath: s3tokBase).appendingPathComponent(snap)
            .appendingPathComponent("model.safetensors")

        let model = try ChatterboxTTSModel.fromPretrained(
            localDir: URL(fileURLWithPath: "/tmp/cbx-fp16"),
            s3TokenizerWeights: s3tokWeights,
            conformerWeights: conformerWeightsURL())

        let golden = try JSONSerialization.jsonObject(
            with: Data(contentsOf: URL(fileURLWithPath: goldenJSON))) as! [String: Any]
        return (model.s3gen, golden)
    }

    // MARK: - Gate 1: CAMPPlus x-vector

    func testCAMPPlusXVectorMatchesGolden() throws {
        let (s3gen, _) = try loadS3Gen()
        let (samples, sr) = try loadWav(refWav)
        // CAMPPlus needs 16 kHz; resample if the clip isn't already.
        let ref16k = sr == 16000 ? samples
            : AudioCommonResample(samples, from: sr, to: 16000)
        let x = s3gen.speakerEncoder.inference(ref16k)
        MLX.eval(x)
        let got = x.reshaped([x.size]).asType(.float32).asArray(Float.self)
        let gold = try readF32(embeddingF32)
        let cos = cosine(got, gold)
        print("[S3Gen] CAMPPlus x-vector cosine = \(cos)")
        XCTAssertGreaterThan(cos, 0.999, "CAMPPlus x-vector cosine=\(cos)")
    }

    // MARK: - Gate 2: HiFTGenerator on the golden mel

    func testHiFTGeneratorWavLengthMatchesGolden() throws {
        let (s3gen, golden) = try loadS3Gen()
        // golden flow mel [1, 80, 63].
        let melFlat = try readF32(melF32)
        let melShape = ((golden["mel"] as! [String: Any])["shape"] as! [Any]).map { ($0 as! NSNumber).intValue }
        let mel = MLXArray(melFlat).reshaped(melShape)  // [1, 80, 63]

        let wav = s3gen.vocoder.inference(mel: mel)
        MLX.eval(wav)
        let goldWavLen = (((golden["wav"] as! [String: Any])["shape"] as! [Any])
            .map { ($0 as! NSNumber).intValue })[1]
        // The golden wav includes the 20 ms trim-fade window; the raw vocoder
        // output length should match it within a couple of frames.
        let gotLen = wav.dim(1)
        print("[S3Gen] HiFTGenerator wav length = \(gotLen) (golden \(goldWavLen))")
        XCTAssertEqual(Double(gotLen), Double(goldWavLen), accuracy: 64,
                       "HiFT wav length \(gotLen) vs golden \(goldWavLen)")

        // Non-silent.
        let arr = wav.reshaped([wav.size]).asType(.float32).asArray(Float.self)
        let rms = (arr.reduce(0) { $0 + Double($1) * Double($1) } / Double(arr.count)).squareRoot()
        XCTAssertGreaterThan(rms, 1e-3, "HiFT output is silent (rms=\(rms))")
    }

    // MARK: - Gate 3: flow mel vs golden (reported)

    func testFlowMelCosineAgainstGolden() throws {
        let (s3gen, golden) = try loadS3Gen()
        let (samples, sr) = try loadWav(refWav)
        // Reference at the two rates the flow conditioning needs.
        let ref24k = sr == 24000 ? samples : AudioCommonResample(samples, from: sr, to: 24000)
        let ref16k = AudioCommonResample(ref24k, from: 24000, to: 16000)
        let ref = s3gen.embedRef(refWav24k: ref24k, refWav16k: ref16k)

        // prompt_feat parity (front-end sanity): cosine vs golden.
        let pfGot = ref.promptFeat.reshaped([ref.promptFeat.size]).asType(.float32).asArray(Float.self)
        let pfGold = try readF32(promptFeatF32)
        let pfCos = cosine(pfGot, pfGold)
        print("[S3Gen] prompt_feat cosine = \(pfCos) (got n=\(pfGot.count), gold n=\(pfGold.count))")

        let speechTokens = (golden["speech_tokens"] as! [Any]).map { ($0 as! NSNumber).intValue }
        let mel = s3gen.flowMel(speechTokens: speechTokens, ref: ref)
        MLX.eval(mel)
        let got = mel.reshaped([mel.size]).asType(.float32).asArray(Float.self)
        let gold = try readF32(melF32)
        let cos = cosine(got, gold)
        print("[S3Gen] flow mel cosine = \(cos) (got shape \(mel.shape), gold n=\(gold.count))")
        // Seeded noise + loaded conformer blocks should make this reproducible;
        // report it and assert a lenient floor (>0.95 acceptable per the brief).
        XCTAssertGreaterThan(cos, 0.95, "flow mel cosine=\(cos)")
    }
}

/// Thin resample shim over AudioCommon's converter.
private func AudioCommonResample(_ s: [Float], from inRate: Int, to outRate: Int) -> [Float] {
    AudioFileLoader.resample(s, from: inRate, to: outRate)
}
